# Generated by Django 5.0.6 on 2024-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded_img/')),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
                ('con_lvl', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
