# Generated by Django 5.0.6 on 2024-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_upload_img_con_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_img',
            name='con_lvl',
            field=models.DecimalField(blank=True, decimal_places=2, default='NULL', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='upload_img',
            name='label',
            field=models.CharField(blank=True, default='NULL', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='upload_img',
            name='status',
            field=models.CharField(blank=True, default='NULL', max_length=12, null=True),
        ),
    ]
