# Generated by Django 5.0.6 on 2024-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_upload_img_con_lvl_alter_upload_img_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_img',
            name='con_lvl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
