# Generated by Django 5.0.6 on 2024-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_upload_img_con_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_img',
            name='con_lvl',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
    ]
