# Generated by Django 5.0.6 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_upload_img_con_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='NULL', null=True, upload_to='')),
                ('date', models.DateField(blank=True, default='NULL', null=True)),
                ('con_lvl', models.CharField(blank=True, default='NULL', max_length=5, null=True)),
                ('label', models.CharField(blank=True, default='NULL', max_length=12, null=True)),
            ],
        ),
    ]
