# Generated by Django 5.0.6 on 2024-07-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='records',
            new_name='saved_records',
        ),
    ]
