# Generated by Django 5.0.6 on 2024-07-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_records_saved_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('con_lvl', models.CharField(blank=True, max_length=5, null=True)),
                ('label', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='saved_records',
        ),
        migrations.AddField(
            model_name='recorddata',
            name='record_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_data', to='my_app.savedrecord'),
        ),
    ]
